version: '3.4'
services:
  dev_python:
    container_name: dev_python
    privileged: true
    environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    - PYQTDESIGNERPATH=/usr/local/pydm-1.6.5:/usr/local/SOL/GUI/sol-widgets/
    - LANG="en_US.UTF-8"
    - LC_ALL="en_US.UTF-8"
    - PYTHONPATH=/usr/local/SOL/scan-utils/:/usr/local/SOL/GUI:/usr/local/SOL/GUI/sol-widgets/
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      args: 
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER: ${USER}
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/${USER}/.Xauthority:rw
      - $HOME:/home/${USER}/
      - $HOME/.ssh:/home/${USER}/.ssh
      - /usr/local/scripts/scan-utils/:/etc/xdg/scan-utils/
      - /home/ABTLUS/lais.carmo/xaru/scan-gui/:/home/${USER}/scan-gui/
    stdin_open: true
    tty: true

