version: '3.2'
services:
  dev_python:
    container_name: dev_python
    privileged: true
    environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER: ${USER}
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/${USER}/.Xauthority:rw
      - $HOME:/home/${USER}/work
    stdin_open: true
    tty: true

